---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install centos-release-scl-rh (CentOS only)
  package:
    name: centos-release-scl-rh
    state: present
    enablerepo: extras
  when: ansible_distribution == 'CentOS'

- name: Enables SCL (RHEL only)
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  when: ansible_distribution == 'Red Hat Enterprise Linux'